
import javax.swing.JLabel;


public class DashboardFrame extends javax.swing.JFrame {

  
    private Account account;
    private JLabel jLabel2;

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame(Account account) {
        this.account = account;
        jLabel2 = new JLabel();
        initComponents();
        if(jLabel2 != null) {
            jLabel2.setText(String.valueOf(account.getBalance()));
        }
        LBbalance.setText(String.valueOf(account.getBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTNwithdraw = new javax.swing.JButton();
        BTNdeposit = new javax.swing.JButton();
        BTNhistory = new javax.swing.JButton();
        BTNquit = new javax.swing.JButton();
        BTNtransfer = new javax.swing.JButton();
        LBbalance = new javax.swing.JLabel();
        BalanceLB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("UNIVERSAL BANK");

        BTNwithdraw.setBackground(new java.awt.Color(51, 51, 51));
        BTNwithdraw.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNwithdraw.setForeground(new java.awt.Color(0, 153, 0));
        BTNwithdraw.setText("WITHDRAW");
        BTNwithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNwithdrawActionPerformed(evt);
            }
        });

        BTNdeposit.setBackground(new java.awt.Color(51, 51, 51));
        BTNdeposit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNdeposit.setForeground(new java.awt.Color(0, 153, 0));
        BTNdeposit.setText("DEPOSIT");
        BTNdeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdepositActionPerformed(evt);
            }
        });

        BTNhistory.setBackground(new java.awt.Color(51, 51, 51));
        BTNhistory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNhistory.setForeground(new java.awt.Color(0, 153, 0));
        BTNhistory.setText("HISTORY");
        BTNhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNhistoryActionPerformed(evt);
            }
        });

        BTNquit.setBackground(new java.awt.Color(51, 51, 51));
        BTNquit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNquit.setForeground(new java.awt.Color(0, 153, 0));
        BTNquit.setText("LOG-OUT");
        BTNquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNquitActionPerformed(evt);
            }
        });

        BTNtransfer.setBackground(new java.awt.Color(51, 51, 51));
        BTNtransfer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNtransfer.setForeground(new java.awt.Color(0, 153, 0));
        BTNtransfer.setText("TRANSFER");
        BTNtransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtransferActionPerformed(evt);
            }
        });

        LBbalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LBbalance.setForeground(new java.awt.Color(0, 153, 0));
        LBbalance.setText("jLabel2");

        BalanceLB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BalanceLB.setText("AVAILABLE BALANCE :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("R");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(BTNquit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNtransfer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNdeposit))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTNwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                                .addComponent(BTNhistory))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BalanceLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BTNdeposit, BTNhistory, BTNquit, BTNtransfer, BTNwithdraw});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceLB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNdeposit)
                    .addComponent(BTNtransfer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNhistory)
                    .addComponent(BTNwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(BTNquit)
                .addGap(40, 40, 40))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BTNdeposit, BTNhistory, BTNquit, BTNtransfer, BTNwithdraw});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNquitActionPerformed
    new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNquitActionPerformed

    private void BTNdepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdepositActionPerformed
        this.dispose();

    // Open the Deposit frame
    Deposit depositFrame = new Deposit(account);
    depositFrame.setVisible(true);

   

    }//GEN-LAST:event_BTNdepositActionPerformed

    private void BTNhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNhistoryActionPerformed
     this.dispose();
        HistoryFrame historyFrame = new HistoryFrame(account); // Pass the account object here
        historyFrame.setVisible(true);
    

    }//GEN-LAST:event_BTNhistoryActionPerformed

    private void BTNwithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNwithdrawActionPerformed
        new WithdrawalFrame(account).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNwithdrawActionPerformed

    private void BTNtransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtransferActionPerformed
        new TransferFrame2(account).setVisible(true);
        
    }//GEN-LAST:event_BTNtransferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        TranfersFrame tf = new TranfersFrame(new Account(300));
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame(tf.account).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNdeposit;
    private javax.swing.JButton BTNhistory;
    private javax.swing.JButton BTNquit;
    private javax.swing.JButton BTNtransfer;
    private javax.swing.JButton BTNwithdraw;
    private javax.swing.JLabel BalanceLB;
    private javax.swing.JLabel LBbalance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    void LBbalance(double balance) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
